# Literature-motivated exchange preparations, not literature wavefunctions.
# See docs/research/vbc_motif_mapping.md for figures and coordinate tables.
using KagomeDMRG

_vbc_site_key(s, origin=(0, 0)) =
    (mod(s[1] - origin[1], 3), mod(s[2] - origin[2], 3), s[3])
_vbc_bond_key(a, b, origin=(0, 0)) =
    minmax(_vbc_site_key(a, origin), _vbc_site_key(b, origin))

function _vbc_class_table(kind::Symbol)
    classes = Dict{Tuple{Tuple{Int,Int,Symbol},Tuple{Int,Int,Symbol}},String}()
    function add(a, b, label)
        key = _vbc_bond_key(a, b)
        haskey(classes, key) && classes[key] != label &&
            error("overlapping VBC bond classes")
        classes[key] = label
    end
    if kind === :hourglass
        # The two triangles share C(x,y). Their centers form the area-three
        # translation lattice generated by (1,1) and (-1,2).
        for n in 0:2
            c = (n, n, :C)
            for (a, b) in (((n,n,:A), (n,n,:B)),
                           ((n,n+1,:A), (n-1,n+1,:B)))
                add(a, b, "bowtie")
                add(a, c, "bowtie")
                add(b, c, "bowtie")
            end
        end
    elseif kind === :windmill
        ring = [(0,0,:B), (1,0,:A), (1,0,:C),
                (0,1,:B), (0,1,:A), (0,0,:C)]
        for i in eachindex(ring)
            add(ring[i], ring[mod1(i+1, length(ring))], "ring")
        end
        wings = [((1,0,:B),(2,-1,:C)), ((1,-1,:C),(1,-1,:A)),
                 ((0,0,:A),(-1,0,:B)), ((-1,1,:B),(-1,1,:C)),
                 ((0,1,:C),(0,2,:A)), ((1,1,:A),(1,1,:B))]
        for (a, b) in wings
            add(a, b, "wing")
        end
        dumbbells = [((-2,2,:B),(-1,2,:A),(-1,2,:B)),
                     ((-1,0,:A),(-1,0,:C),(-1,1,:A)),
                     ((0,2,:C),(0,2,:B),(1,1,:C))]
        for (a, c, b) in dumbbells
            add(a, c, "dumbbell")
            add(c, b, "dumbbell")
        end
    else
        throw(ArgumentError("kind must be :hourglass or :windmill"))
    end
    return classes
end

function _vbc_geometry_records(lattice)
    return [[b.i, b.j, b.wy] for b in lattice.bonds]
end

"""
    vbc_bond_template(lattice; kind=:hourglass, origin=(0,0))

Return `(weights, metadata)` in the lattice's existing bond order. Positive
weights strengthen exchanges in `vbc_prepared_lattice`. The infinite-periodic
bond mean is zero and the maximum positive weight is one. Finite OBC cropping
does not recenter weights. Origin translates the infinite pattern before it
is cropped; winding is retained. Ly must be divisible by three; Lx=1 patches
are allowed for independent small-system checks.

Hourglass selects the six bonds of each shared-C bowtie in Fang et al. Fig.1b;
it is deliberately a motif-selective pin, not all four reported bond classes.
Windmill uses the four geometric classes in Cheng--Li Fig.5. Their correlation
magnitudes set preparation weights only, never a target energy or observable.
No state, charge, or phase claim is made by either construction.
"""
function vbc_bond_template(lattice::KagomeCylinder; kind::Symbol=:hourglass,
                           origin=(0,0))
    length(origin) == 2 && all(x -> x isa Integer && !(x isa Bool), origin) ||
        throw(ArgumentError("origin must contain two integer cell coordinates"))
    lattice.Ly % 3 == 0 || throw(ArgumentError("VBC templates require Ly divisible by three"))
    canonical = kagome_cylinder(lattice.Lx, lattice.Ly)
    lattice.sites == canonical.sites &&
        _vbc_geometry_records(lattice) == _vbc_geometry_records(canonical) ||
        throw(ArgumentError("VBC templates require canonical NN geometry and bond order"))
    ox, oy = mod(origin[1], 3), mod(origin[2], 3)
    table = _vbc_class_table(kind)
    strengths = kind === :hourglass ? Dict("bowtie"=>1.0, "background"=>0.0) :
        Dict("ring"=>0.3722, "wing"=>0.6180, "dumbbell"=>0.4466, "background"=>0.0743)
    mean_strength = kind === :hourglass ? 1/3 :
        (6strengths["ring"] + 6strengths["wing"] + 6strengths["dumbbell"] +
         36strengths["background"])/54
    scale = maximum(values(strengths)) - mean_strength
    labels = String[]
    for b in lattice.bonds
        si, sj = lattice.sites[b.i], lattice.sites[b.j]
        a = (si.x, si.y, si.sublattice)
        c = (sj.x, sj.y + b.wy*lattice.Ly, sj.sublattice)
        push!(labels, get(table, _vbc_bond_key(a, c, (ox, oy)), "background"))
    end
    weights = [(strengths[label] - mean_strength)/scale for label in labels]
    metadata = Dict{String,Any}(
        "schema_version"=>1, "kind"=>String(kind),
        "status"=>"literature_motivated_exchange_preparation_only",
        "literature_wavefunction_reproduction"=>false,
        "origin_cell"=>[Int(ox),Int(oy)],
        "Lx"=>lattice.Lx, "Ly"=>lattice.Ly, "N"=>nsites(lattice),
        "site_order"=>"x,y,A,B,C", "wrap_cell_vector"=>[0,lattice.Ly],
        "primitive_cell_translations"=>kind === :hourglass ? [[1,1],[-1,2]] : [[3,0],[0,3]],
        "motif_unit_cell_sites"=>kind === :hourglass ? 9 : 27,
        "motif_cluster_sites"=>kind === :hourglass ? 5 : 18,
        "periodic_bond_class_counts"=>kind === :hourglass ?
            Dict("bowtie"=>6,"background"=>12) :
            Dict("ring"=>6,"wing"=>6,"dumbbell"=>6,"background"=>36),
        "bond_classes"=>labels, "bond_weights"=>weights,
        "bond_geometry"=>_vbc_geometry_records(lattice),
        "raw_class_strengths"=>strengths,
        "infinite_periodic_mean_strength"=>mean_strength,
        "weight_normalization"=>"(raw - infinite periodic bond mean)/(maximum raw - mean)",
        "finite_obc_recentered"=>false,
        "preparation_rule"=>"Jxy_b=Jz_b=1+lambda*weight_b; all canonical NN bonds retained",
        "source_url"=>kind === :hourglass ? "https://arxiv.org/pdf/2306.09563v1" :
                                               "https://arxiv.org/pdf/2507.20308v1",
        "source_figure"=>kind === :hourglass ? "Fig.1(b), page 2" : "Fig.5, page 9",
        "mapping_limit"=>kind === :hourglass ?
            "Six bowtie bonds selected geometrically; all four reported bond classes are not reproduced" :
            "Four bond classes mapped from the figure; rounded correlations only set a chosen preparation profile")
    return (; weights, metadata)
end

"""
    vbc_prepared_lattice(lattice, template, lambda)

Apply the template to a canonical, isotropic J=1 NN lattice. Lambda=0 returns
exactly its original Jxy/Jz, endpoints, winding and sites. This is a temporary
exchange perturbation, and must be removed before a nearest-neighbor comparison.
"""
function vbc_prepared_lattice(lattice::KagomeCylinder, template, lambda::Real)
    lambda isa Bool && throw(ArgumentError("lambda must be a finite nonnegative real"))
    strength = Float64(lambda)
    isfinite(strength) && strength >= 0 ||
        throw(ArgumentError("lambda must be a finite nonnegative real"))
    canonical = kagome_cylinder(lattice.Lx, lattice.Ly)
    lattice.sites == canonical.sites &&
        _vbc_geometry_records(lattice) == _vbc_geometry_records(canonical) &&
        all(b -> b.Jxy == 1.0 && b.Jz == 1.0, lattice.bonds) ||
        throw(ArgumentError("preparation must start from the canonical isotropic J=1 NN lattice"))
    weights = template.weights
    length(weights) == length(lattice.bonds) && all(isfinite, weights) ||
        throw(ArgumentError("template weights must be finite and match the bond count"))
    template.metadata["Lx"] == lattice.Lx && template.metadata["Ly"] == lattice.Ly &&
        template.metadata["bond_geometry"] == _vbc_geometry_records(lattice) ||
        throw(ArgumentError("template geometry does not match the lattice"))
    couplings = 1 .+ strength .* weights
    all(j -> isfinite(j) && j > 0, couplings) ||
        throw(ArgumentError("preparation requires positive finite antiferromagnetic exchanges"))
    bonds = [Bond(b.i,b.j,couplings[k],couplings[k],b.wy) for (k,b) in enumerate(lattice.bonds)]
    return KagomeCylinder(lattice.Lx,lattice.Ly,copy(lattice.sites),bonds)
end
